services:
  postgres:
    image: postgres:15-alpine
    container_name: expenses_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  expenses-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expenses-management
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: expenses_management
      LOG_LEVEL: 0
      PAYMENT_PROCESSOR_URL: "https://1620e98f-7759-431c-a2aa-f449d591150b.mock.pstmn.io/v1/payments"
      JWT_KEY: "jwtsecretkey"

  adminer:
    image: adminer:latest
    container_name: expenses-management-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: